/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Database.MenuOperation;
import Database.OrderPaymentOperation;
import Database.ReviewOperation;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author SSC
 */
public class GiveReviewForm extends javax.swing.JFrame {

    /**
     * Creates new form GiveReviewForm
     */
    ButtonGroup menuReviButtonGroup = new ButtonGroup();
    ButtonGroup deliveryReviButtonGroup = new ButtonGroup();
    ButtonGroup applicationReviButtonGroup = new ButtonGroup();

    public GiveReviewForm() {
        initComponents();
        Useables.Useable.makeImageFixToScreen("src//Images//treebg.jpg", backgroundImage, backgroundImage.getWidth(), backgroundImage.getHeight() + 1000);
        menuReviButtonGroup.add(badMenu);
        menuReviButtonGroup.add(perfectMenu);
        menuReviButtonGroup.add(goodMenu);
        deliveryReviButtonGroup.add(badDelivery);
        deliveryReviButtonGroup.add(perfectDelivery);
        deliveryReviButtonGroup.add(goodDelivery);
        applicationReviButtonGroup.add(perfectApplication);
        applicationReviButtonGroup.add(badApplication);
        applicationReviButtonGroup.add(goodApplication);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        reviewsButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        cartButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        perfectMenu = new javax.swing.JRadioButton();
        goodMenu = new javax.swing.JRadioButton();
        badMenu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        perfectDelivery = new javax.swing.JRadioButton();
        goodDelivery = new javax.swing.JRadioButton();
        badDelivery = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        perfectApplication = new javax.swing.JRadioButton();
        goodApplication = new javax.swing.JRadioButton();
        badApplication = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        checkOutButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Review");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        reviewsButton.setBackground(new java.awt.Color(255, 255, 255));
        reviewsButton.setForeground(Color.BLACK);
        reviewsButton.setText("Review");
        reviewsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewsButtonActionPerformed(evt);
            }
        });

        orderButton.setBackground(new java.awt.Color(255, 255, 255));
        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.setToolTipText("");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        menuButton.setBackground(new java.awt.Color(255, 255, 255));
        menuButton.setForeground(Color.BLACK);
        menuButton.setText("Create Order");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        cartButton.setBackground(new java.awt.Color(255, 255, 255));
        cartButton.setForeground(Color.BLACK);
        cartButton.setText("Shoping Cart");
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(menuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reviewsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(homeButton)
                    .addComponent(reviewsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderButton)
                    .addComponent(menuButton)
                    .addComponent(cartButton))
                .addGap(77, 77, 77))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 50));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 46)); // NOI18N
        jLabel1.setText("You can review our shop here");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 60));

        jLabel2.setBackground(new java.awt.Color(102, 0, 153));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setText("Rate our menu ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 40));

        perfectMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perfectMenu.setSelected(true);
        perfectMenu.setLabel("Perfect");
        perfectMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfectMenuActionPerformed(evt);
            }
        });
        getContentPane().add(perfectMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        goodMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goodMenu.setLabel("Good");
        goodMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodMenuActionPerformed(evt);
            }
        });
        getContentPane().add(goodMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        badMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        badMenu.setLabel("Bad");
        badMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badMenuActionPerformed(evt);
            }
        });
        getContentPane().add(badMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("Rate our delivery ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 40));

        perfectDelivery.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perfectDelivery.setSelected(true);
        perfectDelivery.setLabel("Perfect");
        getContentPane().add(perfectDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        goodDelivery.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goodDelivery.setLabel("Good");
        getContentPane().add(goodDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        badDelivery.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        badDelivery.setLabel("Bad");
        badDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badDeliveryActionPerformed(evt);
            }
        });
        getContentPane().add(badDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("Rate our application");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        perfectApplication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perfectApplication.setSelected(true);
        perfectApplication.setLabel("Perfect");
        perfectApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfectApplicationActionPerformed(evt);
            }
        });
        getContentPane().add(perfectApplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        goodApplication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goodApplication.setText("Good");
        getContentPane().add(goodApplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        badApplication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        badApplication.setLabel("Bad");
        badApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badApplicationActionPerformed(evt);
            }
        });
        getContentPane().add(badApplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setText("Any notes/conflicts?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane1.setViewportView(notes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 630, 110));

        checkOutButton.setBackground(new java.awt.Color(255, 255, 255));
        checkOutButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkOutButton.setForeground(Color.BLACK);
        checkOutButton.setText("Submit Review");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 240, -1));

        backgroundImage.setText("jLabel5");
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 730, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reviewsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewsButtonActionPerformed
        // TODO add your handling code here:
        ViewCustomerReviews viewAllReviewsForm = new ViewCustomerReviews();
        this.setVisible(false);
        viewAllReviewsForm.setVisible(true);
    }//GEN-LAST:event_reviewsButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        OrderHistoryForCustomer ordersHistoryForm = new OrderHistoryForCustomer();
        ordersHistoryForm.setVisible(true);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.setVisible(false);
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CustomerHome home = new CustomerHome();
        home.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CreateOrderForm itemsForm = new CreateOrderForm();
        itemsForm.setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CartForm cartForm = new CartForm();
        cartForm.setVisible(true);
    }//GEN-LAST:event_cartButtonActionPerformed

    private void perfectMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfectMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfectMenuActionPerformed

    private void goodMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goodMenuActionPerformed

    private void badMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badMenuActionPerformed

    private void badDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badDeliveryActionPerformed

    private void perfectApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfectApplicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfectApplicationActionPerformed

    private void badApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badApplicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badApplicationActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
        String menuReview = perfectMenu.isSelected() ? "Perfect" : goodMenu.isSelected() ? "Good" : "Bad";
        String deliveryReview = perfectDelivery.isSelected() ? "Perfect" : goodDelivery.isSelected() ? "Good" : "Bad";
        String applicationReview = perfectApplication.isSelected() ? "Perfect" : goodApplication.isSelected() ? "Good" : "Bad";

        ReviewOperation.insertReviewData(OrderPaymentOperation.getMaxOrderId(), menuReview, deliveryReview, applicationReview, notes.getText());
        Useables.Useable.ShowSuccessErrorMessage("Review Added Successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        new CustomerHome().setVisible(true);
    }//GEN-LAST:event_checkOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiveReviewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiveReviewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiveReviewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiveReviewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiveReviewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JRadioButton badApplication;
    private javax.swing.JRadioButton badDelivery;
    private javax.swing.JRadioButton badMenu;
    private javax.swing.JButton cartButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JRadioButton goodApplication;
    private javax.swing.JRadioButton goodDelivery;
    private javax.swing.JRadioButton goodMenu;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton menuButton;
    private javax.swing.JTextArea notes;
    private javax.swing.JButton orderButton;
    private javax.swing.JRadioButton perfectApplication;
    private javax.swing.JRadioButton perfectDelivery;
    private javax.swing.JRadioButton perfectMenu;
    private javax.swing.JButton reviewsButton;
    // End of variables declaration//GEN-END:variables
}
