/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Database.OrderPaymentOperation;
import ModalClasses.HomeDelivery;
import ModalClasses.Payment;
import ModalClasses.ShopDelivery;
import java.awt.Color;
import java.util.Date;
import javax.swing.JRadioButton;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author SSC
 */
public class PaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
        Useables.Useable.makeImageFixToScreen("src//Images//treebg.jpg", backgroundImage, backgroundImage.getWidth(), backgroundImage.getHeight() + 1000);
        totalPrice.setText("₪ : " + OrderPaymentOperation.calculateTotalCartPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        reviewsButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        cartButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        deliveredHome = new javax.swing.JRadioButton();
        deliveredShop = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        cardNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ccvNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        expMonth = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        expyear = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        reviewsButton.setBackground(new java.awt.Color(255, 255, 255));
        reviewsButton.setForeground(Color.BLACK);
        reviewsButton.setText("Review");
        reviewsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewsButtonActionPerformed(evt);
            }
        });

        orderButton.setBackground(new java.awt.Color(255, 255, 255));
        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.setToolTipText("");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        menuButton.setBackground(new java.awt.Color(255, 255, 255));
        menuButton.setForeground(Color.BLACK);
        menuButton.setText("Create Order");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        cartButton.setBackground(new java.awt.Color(255, 255, 255));
        cartButton.setForeground(Color.BLACK);
        cartButton.setText("Shoping Cart");
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(menuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reviewsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(homeButton)
                    .addComponent(reviewsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderButton)
                    .addComponent(menuButton)
                    .addComponent(cartButton))
                .addGap(77, 77, 77))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 50));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Enter your credit card information below ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 330, 45));

        totalPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(51, 51, 255));
        totalPrice.setText("₪: 1000");
        totalPrice.setToolTipText("");
        getContentPane().add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 116, 36));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(135, 103, 82));
        jLabel4.setText("Ordering ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 70));

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Click to continue ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, 60));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel5.setText("would you like for the purchase to be delivered or handed in the shop ?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 587, 43));

        deliveredHome.setSelected(true);
        deliveredHome.setText("Delivered");
        deliveredHome = new JRadioButton("Delivered",true);
        deliveredHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveredHomeActionPerformed(evt);
            }
        });
        getContentPane().add(deliveredHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        deliveredShop.setText("at the shop");
        deliveredShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveredShopActionPerformed(evt);
            }
        });
        getContentPane().add(deliveredShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));
        radioGroup.add(deliveredShop);
        radioGroup.add(deliveredHome);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("credit card number");

        jLabel7.setText("CVV number");

        expMonth.setText(" ");
        expMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expMonthActionPerformed(evt);
            }
        });

        jLabel8.setText("expiration month");

        jLabel9.setText("expiration year");

        expyear.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccvNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(expMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(expyear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccvNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expyear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 360, 160));

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addressLabel.setText("Address :");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 90, 36));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Your total is :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 116, 36));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 250, 30));

        backgroundImage.setText("jLabel1");
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 690, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reviewsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewsButtonActionPerformed
        // TODO add your handling code here:
        ViewCustomerReviews viewAllReviewsForm = new ViewCustomerReviews();
        this.setVisible(false);
        viewAllReviewsForm.setVisible(true);
    }//GEN-LAST:event_reviewsButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        OrderHistoryForCustomer ordersHistoryForm = new OrderHistoryForCustomer();
        ordersHistoryForm.setVisible(true);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.setVisible(false);
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CustomerHome home = new CustomerHome();
        home.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CreateOrderForm itemsForm = new CreateOrderForm();
        itemsForm.setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CartForm cartForm = new CartForm();
        cartForm.setVisible(true);
    }//GEN-LAST:event_cartButtonActionPerformed

    public boolean validateInfo() {

        try {
            if (ccvNumber.getText().length() != 3) {
                Useables.Useable.ShowSuccessErrorMessage("CCV Number should be 3 digits", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            Integer.parseInt(ccvNumber.getText());
        } catch (Exception ex) {
            Useables.Useable.ShowSuccessErrorMessage("CCV Number should be  digits", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        int month = 0;
        int year = 0;
        try {

            month = Integer.parseInt(expMonth.getText());
            if (month < 1 || month > 12) {
                Useables.Useable.ShowSuccessErrorMessage("EXP Month should be  in between 1 ~ 12", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (Exception ex) {
            Useables.Useable.ShowSuccessErrorMessage("EXP Month should be  digits", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {

            year = Integer.parseInt(expyear.getText());
            if (year < 2022) {
                Useables.Useable.ShowSuccessErrorMessage("EXP Year should be greater than 2022", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (Exception ex) {
            Useables.Useable.ShowSuccessErrorMessage("EXP Year should be  digits", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if ((month - 1) < new Date().getMonth()) {
            Useables.Useable.ShowSuccessErrorMessage("Card is expired.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (ccvNumber.getText().equals("")) {
            Useables.Useable.ShowSuccessErrorMessage("CCV Number required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (cardNumber.getText().equals("")) {
            Useables.Useable.ShowSuccessErrorMessage("Card Number required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (expMonth.getText().equals("")) {
            Useables.Useable.ShowSuccessErrorMessage("Exp Month required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (expyear.getText().equals("")) {
            Useables.Useable.ShowSuccessErrorMessage("Exp year required", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!validateInfo()) {

        } else {
            if (deliveredHome.isSelected()) {
                if (address.getText().equals("")) {
                    Useables.Useable.ShowSuccessErrorMessage("Address required", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            Payment payment = new ShopDelivery(0, cardNumber.getText(), ccvNumber.getText(), expMonth.getText(), expyear.getText());
            if (deliveredHome.isSelected()) {
                payment = new HomeDelivery(0, cardNumber.getText(), ccvNumber.getText(), expMonth.getText(), expyear.getText(), address.getText());
            }

            if (OrderPaymentOperation.insertPaymentData(payment) >= 0) {
                Useables.Useable.ShowSuccessErrorMessage("Order Successfully Placed", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                Useables.Useable.cart.clear();
                new GiveReviewForm().setVisible(true);
            } else {
                Useables.Useable.ShowSuccessErrorMessage("Order Not Successfully Placed", "Error", JOptionPane.ERROR_MESSAGE);

            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void deliveredHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveredHomeActionPerformed
        // TODO add your handling code here:
        addressLabel.setVisible(true);
        address.setVisible(true);
    }//GEN-LAST:event_deliveredHomeActionPerformed

    private void deliveredShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveredShopActionPerformed
        // TODO add your handling code here:
        addressLabel.setVisible(false);
        address.setVisible(false);
    }//GEN-LAST:event_deliveredShopActionPerformed

    private void expMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentForm().setVisible(true);
            }
        });
    }
    ButtonGroup radioGroup = new ButtonGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JButton cartButton;
    private javax.swing.JTextField ccvNumber;
    private javax.swing.JRadioButton deliveredHome;
    private javax.swing.JRadioButton deliveredShop;
    private javax.swing.JTextField expMonth;
    private javax.swing.JTextField expyear;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton reviewsButton;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
